### ISSUE TITLE
Error page Template Render Issue

### ISSUE THREAD

**Issue by tomalex0** [krakenjs/kraken-js#335] opened 2015-02-20 17:04 UTC
I'm trying to run app in `development` mode with templates pointed to `.build\templates` folder, dust files are converted to js (`.build\templates\US\en`) and  home  page is loaded fine 

But if i try to  enter wrong url for which i'm expecting 404, but below error is shown( everything used worked fine  in dust mode  (`public\templates`) )
```

Not sure if i'm  missing any config 

Error: Could not load template 
    at Object.onLoad (c:\Projects\myapp\node_modules\engine-munger\view\js.js:38:22)
    at Object.cache.get (c:\Projects\myapp\node_modules\engine-munger\lib\cache.js:59:14)
    at spclOnLoad (c:\Projects\myapp\node_modules\engine-munger\lib\munger.js:75:9)
    at c:\Projects\myapp\node_modules\adaro\lib\reader\file.js:62:16
    at onChunk (c:\Projects\myapp\node_modules\adaro\lib\patch\index.js:69:29)
    at Chunk.map (c:\Projects\myapp\node_modules\dustjs-linkedin\lib\dust.js:587:7)
    at c:\Projects\myapp\node_modules\adaro\lib\patch\index.js:91:39
    at Object.dust.load [as __cabbage__] (c:\Projects\myapp\node_modules\dustjs-linkedin\lib\dust.js:137:14)
    at Object.cabbage [as load] (c:\Projects\myapp\node_modules\adaro\lib\patch\index.js:98:21)
    at Object.dust.render (c:\Projects\myapp\node_modules\dustjs-linkedin\lib\dust.js:92:12)
```

This is how my config looks
```
"express": {
        "view cache": false,
        "view engine": "js",
        "views": "path:./.build/templates"
    },
"i18n": {
        "contentPath": "path:./locales",
        "fallback": "en-US"
    },
"view engines": {
        "js": {
            "module": "engine-munger",
            "renderer": {
                "method": "js",
                "arguments": [
                    { "cache": true },
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "specialization": "config:specialization",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    },
"middleware": {

        "static": {
            "module": {
                "arguments": [ "path:./.build" ]
            }
        },
        "compress" : {
            "enabled": true,
            "priority": 10,
            "module" : "compression"
        },
        "router": {
            "module": {
                "arguments": [
                    { "directory": "path:./routes" }
                ]
            }
        },

        
        "expressView": {
            "priority": 100,
            "enabled": true,
            "module": {
                "name": "engine-munger/lib/expressView"
            }
        },
        

        "fileNotFound": {
            "enabled": true,
            "priority": 130,
            "module": {
                "name": "kraken-js/middleware/404",
                "arguments": [ "errors/404" ]
            }
        },

        "serverError": {
            "enabled": true,
            "priority": 140,
            "module": {
                "name": "kraken-js/middleware/500",
                "arguments": [ "errors/500" ]
            }
        },

        "accessDenied": {
            "enabled": true,
            "priority": 150,
            "module": {
                "name": "path:./lib/403",
                "arguments": [ "errors/403" ]
            }
        },
        "logger": {
            "module": {
                "name": "morgan",
                "arguments": [
                    ":remote-addr - :remote-user [:date[clf]] ':method :url HTTP/:http-version' :status :res[content-length] ':referrer' ':user-agent' :req[header] :res[header] :response-time ms"
                ]
            }
        },
        "appsec": {
            "enabled": true,
            "priority": 111,
            "module": {
                "name": "lusca",
                "arguments": [
                    {
                        "xframe": "SAMEORIGIN",
                        "p3p": true,
                        "csp": true
                    }
                ]
            }
        }
    }
```

This is my npm module versions

```
{
    "adaro": "^0.1.5",
    "async": "^0.9.0",
    "compression": "^1.2.2",
    "cookie": "^0.1.2",
    "cookie-parser": "^1.3.3",
    "dustjs-helpers": "^1.2.0",
    "dustjs-linkedin": "^2.3.6",
    "engine-munger": "^0.2.0",
    "express": "^4.3.0",
    "express-session": "^1.9.3",
    "kraken-devtools": "^1.0.0",
    "kraken-js": "^1.0.1",
    "less": "^1.6.1",
    "localizr": "^0.1.0",
    "moment": "^2.8.4",
    "moment-range": "^1.0.5",
    "morgan": "^1.5.0",   
    "path-to-regexp": "^1.0.1",
    "request": "^2.51.0",
    "request-promise": "^0.3.2",
    "simple-oauth2": "^0.2.1",
    
  }
```

**Comment by jasisk** [comment] 2015-02-20 19:36
Do you have a `./public/templates/errors/404.dust`?

**Comment by tomalex0** [comment] 2015-02-20 21:03
yes i do have.

If  templates is pointed to `public/template` and in `dust` mode it works fine.

**Comment by jasisk** [comment] 2015-02-20 21:43
Have you built your assets in production (`grunt build`)?

**Comment by tomalex0** [comment] 2015-02-20 22:21
yes, i do see templates under `.build\templates\US\en` after `grunt build`

**Comment by aredridel** [comment] 2015-02-25 15:16
Do you have `.build\templates\US\en\errors\404.js` ?

**Comment by tomalex0** [comment] 2015-02-26 09:05
yes, it looks like below

```
(function(){dust.register("errors/404",body_0);var blocks={"body":body_1};function body_0(chk,ctx){ctx=ctx.shiftBlocks(blocks);return chk.p("layouts/master",ctx,{});}body_0.__dustBody=!0;function body_1(chk,ctx){ctx=ctx.shiftBlocks(blocks);return chk.w("<h1>File not found</h1><p>The URL <code>").f(ctx.get(["url"], false),ctx,"h").w("</code> did not resolve to a route.</p>");}body_1.__dustBody=!0;return body_0;})();
```

**Comment by aredridel** [comment] 2015-02-26 14:54
Try upgrading to adaro 0.1.7

**Comment by tomalex0** [comment] 2015-02-27 20:27
I have updated adaro version, still no luck.

**Comment by aredridel** [comment] 2015-02-27 20:29
Nuts, alright.

**Comment by tomalex0** [comment] 2015-02-27 20:34
This is how `view engines` look, do i need to make some change in this  specific to adaro
```
"view engines": {
        "js": {
            "module": "engine-munger",
            "renderer": {
                "method": "js",
                "arguments": [
                    { "cache": true },
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "specialization": "config:specialization",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    }
```


```
"view engines": {
        "js": {
            "module": "adaro",
            "renderer": {
                "method": "js",
                "arguments": [
                    { "cache": true },
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "specialization": "config:specialization",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    },
```

**Comment by aredridel** [comment] 2015-02-27 20:40
Use `engine-munger` for i18n support. Adaro 2.0 will integrate support, but is a bigger change.

**Comment by tomalex0** [comment] 2015-02-27 20:45
When i remove below config from middleware


```
 "fileNotFound": {
            "enabled": true,
            "priority": 130,
            "module": {
                "name": "kraken-js/middleware/404",
                "arguments": [ "errors/404" ]
            }
        },

        "serverError": {
            "enabled": true,
            "priority": 140,
            "module": {
                "name": "kraken-js/middleware/500",
                "arguments": [ "errors/500" ]
            }
        }
```

page will be shown as `Cannot GET /errorpage` for `myapp.com/errorpage`

**Comment by aredridel** [comment] 2015-02-27 20:48
Oh excellent. The serverError middleware is terrible. Remove it!

But is there more than that logged?

**Comment by tomalex0** [comment] 2015-02-27 20:56
But i was wondering how can i  show   404  and other error pages correctly in `js` mode? 

In `dust` mode everything used to work.

**Comment by aredridel** [comment] 2015-02-27 21:06
Yeah, I'm not sure there. I need to figure out how to reproduce this -- haven't had a lot of time since it's on Windows. If you've a minimal app that shows this off It'd help me a bunch to track it down.

**Comment by tomalex0** [comment] 2015-02-27 21:07
let me try to set something iup

**Comment by aredridel** [comment] 2015-02-27 21:08
Thank you! If you can get a simple repro app, I can take it and run with it.

**Comment by tomalex0** [comment] 2015-02-27 22:24
I tried it with base version which i have used to  add more features, and it worked fine in `js` mode.

Now i will have to compare , if i'm doing something wrong.

Thanks a lot  for the support. I will update when i  fix the issue.

I might  be doing something crazy in dust files.

**Comment by jasisk** [comment] 2015-03-12 15:50
Closing since it's been a week. Happy to reopen if necessary.

**Closed by jasisk** 2015-03-12 15:50 UTC
Labels: in progress, support

**Comment by tomalex0** [comment] 2015-04-01 19:12
I have cleaned up the code for new version and  `error page template` started working fine in `.build` folder.

**Comment by jasisk** [comment] 2015-04-01 19:13
Glad to hear it. :grinning:
