### ISSUE TITLE
Unable to send params with same name when form has "multi-part/form-data"

### ISSUE THREAD

**Issue by emanuelsaringan** [krakenjs/kraken-js#190] opened 2014-04-23 10:24 UTC
Hi. 

I wish to POST form fields with the same name to KrakenJS. Using normal forms without enctype="multipart/form-data", I get them as an array (which is the correct behavior). However, when I am using a form with enctype="multipart/form-data", I only receive the first field in the middleware. 

Is this a bug of KrakenJS or NodeJS? Thanks.

**Comment by jasisk** [comment] 2015-10-07 19:45
Closing due to age.
Issue related to middleware execution order.

**Closed by jasisk** 2015-10-07 19:45 UTC

**Comment by kumarrishav** [comment] 2016-11-30 19:04
for multipart, the issue is with formidable module. It's not able to parse multivalue array. For ex - 'name[first]' = 'x' ;  'name[last]' = 'y' .
it's not able to parse it as name : {first : 'x', last: 'y'} ; So, i had to write a middleware to parse req.body ;
