### ISSUE TITLE
issue with localization and dust context helper with Dust makara2

### ISSUE THREAD

**Issue by lebretr** [krakenjs/kraken-js#428] opened 2015-11-04 16:17 UTC
Hello,

I want translate codes (ex: MissingCredential, UnknownUser,...) with a good message ( example: 
US MissingCredential : 'Please enter Login and Password', FR MissingCredential : 'Veuillez saisir votre identifiant et votre mot de passe', ...)

For this, I use a dust context helper (http://www.dustjs.com/guides/context-helpers/) and the localization.

If I use only localization or only a dust context helper, it's ok
but when I use the both, the server not response (and i haven't got error in console)

You can view an app example with this error here: https://github.com/lebretr/dust_error_local

Example:

controller/index.js
```js
var model = {
    messages=['firstMessage','secondMessage'],
    model.messagesHelper=function(chunk, context, bodies, params) {
	    if( Object.prototype.toString.call( this.messages ) === '[object Array]' ) {
	        var messages = context.get("messages");

	        messages.forEach(function(message) {
	            chunk.render(bodies.block, context.push({
	                "msgCode": message
	            }));
	        });
	    }
	}
};
res.render('index', model);
```

index.dust
```
{#messagesHelper}
	{@pre type="content" key="msgCode"/}
	<br/>
{/messagesHelper}
```

my config:
node : V4.2.2 64bit
OS: Linux Mint 17.2 64 bit
generator-kraken: V2.1.0

```
     ,'""`. 
hh  / _  _ \
    |(@)(@)|   Release the Kraken!
    )  __  (
   /,'))((`.\ 
  (( ((  )) ))
   `\ `)(' /'

Tell me a bit about your application:

? Name app
? Description dust problem
? Author lebretr
? Template library? Dust (via Makara 2)
? Include i18n support? Yes
? Front end package manager ? No
? CSS preprocessor library? LESS
? JavaScript library? None
```

**Comment by grawk** [comment] 2015-11-04 16:27
I'm cloning your app and looking now.

**Comment by grawk** [comment] 2015-11-04 17:29
Thanks for the sample app. I'm able to reproduce this. There is likely something like infinite recursion going on, between the context helper and the `@pre` helper. As such, we should deal with this bug here:
https://github.com/krakenjs/dust-message-helper

I'm going to close this issue since it wouldn't require any code changes in kraken-js

**Closed by grawk** 2015-11-04 17:29 UTC

**Comment by lebretr** [comment] 2015-11-04 17:57
Thank you for your help.
