### ISSUE TITLE
config import override not working 

### ISSUE THREAD

**Issue by skoranga** [krakenjs/kraken-js#328] opened 2015-01-28 22:26 UTC
Hi team,

Looks like bug.
Refactoring all the middleware configs into different config file (middlewares.json) and importing it as  `"middleware": "import:./middleware.json"` in config.json, will not work if one try to override middleware config for one specific environment.

**Comment by pvenkatakrishnan** [comment] 2015-01-28 22:28
hmmm i think there is a test to show this should work. let me check

**Comment by pvenkatakrishnan** [comment] 2015-01-28 22:29
and this would be an issue for confit

**Comment by totherik** [comment] 2015-01-28 22:47
I'm not able to reproduce, so maybe a test case/example would be helpful. I'm starting a kraken-js app with the following configuration, and printing the value of `"myconfig:mykey"` in my `onconfig` handler:

```javascript
// a.json
{
  "mykey": "A"
}
```

```javascript
// b.json
{
  "mykey": "B"
}
```

```javascript
// c.json
{
  "mykey": "C"
}
```

```javascript
// config.json
{
  "myconfig": "import:./c.json"
}
```

```javascript
// development.json
{
  "myconfig": "import:./a.json"
}
```

```javascript
// test.json
{
  "myconfig": "import:./b.json"
}
```


#### Default (implicit `dev` mode)
```bash
$ npm start
A
```

#### Test
```bash
$ NODE_ENV=test npm start
B
```

#### Production
```bash
$ NODE_ENV=production npm start
C
```

**Comment by skoranga** [comment] 2015-01-28 22:50
let me create a small test case

**Comment by pvenkatakrishnan** [comment] 2015-01-28 22:58
working example here: https://github.com/pvenkatakrishnan/sample

**Comment by skoranga** [comment] 2015-01-28 23:06
Yeah. same here as well :) https://github.com/skoranga/krakentestapp

uncomment this line https://github.com/skoranga/krakentestapp/blob/master/config/config.json#L33 and comment the other middleware config

**Comment by pvenkatakrishnan** [comment] 2015-01-28 23:23
@skoranga only thing is mine works. I changed the commit to look similar to what you are doing and still works. let me poke around your project, which i see failing.

**Comment by skoranga** [comment] 2015-01-28 23:25
You have development middleware commented out - https://github.com/pvenkatakrishnan/sample/blob/master/config/development.json#L27

**Comment by pvenkatakrishnan** [comment] 2015-01-28 23:33
yep figured out.. looking at it... so far the `router` middleware is somehow picking the default settings in `kraken` and not the overridden one is what i've found, unsure why

**Comment by skoranga** [comment] 2015-01-28 23:37
My take is something is off with config merge involving env specific files and imports.

**Comment by totherik** [comment] 2015-01-28 23:37
@skoranga can you please try to articulate the unexpected behavior a little more clearly?

When I run the app as you described, in dev mode the middleware in `development.json` is merged with kraken defaults as expected. It overrides the string value in `config.json` as the handlers are not resolved per file and an object realistically can't be merged with a string.

Subsequently, when I run with `NODE_ENV=test` the contents of `middeware.json` are loaded by `config.json` and merged with kraken defaults as expected (and contents of `development.json` are ignored).

What is not working as you expect?

**Comment by skoranga** [comment] 2015-01-28 23:42
Hi @totherik, did you try uncommenting https://github.com/skoranga/krakentestapp/blob/master/config/config.json#L33 and commenting out https://github.com/skoranga/krakentestapp/blob/master/config/config.json#L35-L75? I think @pvenkatakrishnan can also reproduce the behavior.

**Comment by totherik** [comment] 2015-01-28 23:42
Yes, I see the behavior. I'm asking what's behaving not as you expect.

**Comment by skoranga** [comment] 2015-01-28 23:44
My understanding is should merge the middleware configs regardless of inline or import.

**Comment by totherik** [comment] 2015-01-28 23:51
Currently the two operations are orthogonal and happen in 2 phases: files are merged (via `addDefault` or `addOverride`) and then shortstop handlers are resolved. In this case the files are merged and the string `"import:./middleware.json"` is overwritten by the env-specific object, as objects and strings realistically can't be merged.

Is this a feature request to resolve some shortstop handlers (e.g. `import:`) prior to merge, and some handlers (e.g. `config:`)?

**Comment by pvenkatakrishnan** [comment] 2015-01-28 23:58
@skoranga we just discussed. The behavior is such that the strings get merged as is in the intial phases, and only on `confit.create` do the shortstop handlers get resolved. At this time middleware is already replaced to , `"middleware": {}` or in my case `"middleware": "import:/midware-dev.json"` that is in `development.json`. So it always was designed to work this way. But i do see value in this request. I am converting this thread into feature request to add that support in.

**Comment by pvenkatakrishnan** [comment] 2015-01-29 20:14
ok after a first iteration of it, this will have to change the interface to confit to be async.
The reason being, on every file load, we would have to immediately resolve `import` shortstop handler which is async.

**Comment by skoranga** [comment] 2015-01-29 22:02
thanks @pvenkatakrishnan for the update.

**Comment by totherik** [comment] 2015-02-03 20:10
Can't `import` be switched to run synchronously? It shouldn't have any backward-compatibility implications and for this type of use-case I don't expect performance should be a problem. Thoughts?

Also, can we close this issue and create an enhancement issue against confit directly?

**Comment by totherik** [comment] 2015-02-03 20:12
Ahh, I forgot that even though shortstop supports synchronous handlers, the resolution api is async. Ugh.

**Comment by pvenkatakrishnan** [comment] 2015-02-03 20:15
yes to both @totherik

**Comment by pvenkatakrishnan** [comment] 2015-02-03 20:17
Moving to confit as an enhancement.

**Closed by pvenkatakrishnan** 2015-02-03 20:17 UTC
Labels: enhancement
